### ISSUE TITLE
Unable to build the app with couchbase-lite-iOS ForestDB version 

### ISSUE THREAD

**Issue by hideki** [couchbaselabs/ToDoLite-iOS#24]
Steps to reproduce:
1. Build couchbase-lite-iOS Framework from forestdb branch
2. Build ToDoLite-iOS with ForestDB version of couchbase-lite-iOS framework.
3. See following errors
- /Users/hideki/github-forestdb/ToDoLite-iOS/ToDoLite/AppDelegate.m:163:22: No visible @interface for 'CBLManager' declares the selector 'replaceDatabaseNamed:withDatabaseFile:withAttachments:error:'
- /Users/hideki/github-forestdb/ToDoLite-iOS/ToDoLite/AppDelegate.m:401:18: No visible @interface for 'CBLManager' declares the selector 'replaceDatabaseNamed:withDatabaseFile:withAttachments:error:'

Note: According to @pasin , the method signature of ForestDB version  is different from SQLite version.

**Comment by pasin** [comment]
Closed as fixed.
