### ISSUE TITLE
Empty screen while offline

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/ToDoLite-iOS#41]
I don't know how to reproduce this, but I'll report it anyway just in case.

I don't know which version I have installed, it may be from the master branch or it may be from the app store (I wish it showed the version somewhere!)

Here's what happened:

* I don't believe I'd used the app recently, so it might have been the first run since a phone restart
* I opened the app while offline
* The "TodoLists" screen was blank, it showed none of my lists.
* I forced-quit the app 
* I re-opened it, and it gave me the "facebook login" screen. 
* Since I was offline, I couldn't login, so I was basically stuck.

**Comment by pasin** [comment]
I believe this was fixed.
