### ISSUE TITLE
ToDo lite app doesn't display all the users with whom the task can be shared

### ISSUE THREAD

**Issue by ashvindersingh** [couchbaselabs/ToDoLite-iOS#47]
- Clone the todo lite repo. 
- Change the kSyncGatewayUrl  to @"http://Your_Sync_gateway_ip:4984/todos" in AppDelegate.m
- Start the syncgateway 1.1 with todolite.json. Defined below. 
- Build, compile and run Todo lite app with the 1.1 couchbase lite framework on two devices
- Login with different credentials into Todo lite, say user1@gmail.com on device1, user2@gmail.com on device2
- As a user1, create a task and try to share it with User2. 

App does not display other user,user2 when pressed share button.

**Comment by pasin** [comment]
I couldn't reproduce the issue.

**Comment by ashvindersingh** [comment]
Starting 1.1 release, we need to have "interface": ":4984" in sync gateway config.json. The todo lite config.json did not have this flag causing the no syncing of the data. After adding this flag I was able to sync successfully between clients.

**Comment by tleyden** [comment]
@ashvindersingh / @pasin: I added https://github.com/couchbaselabs/couchbase-mobile-portal/issues/187 to update the docs regarding this confusing change in behavior.  Thanks for documenting this in a ticket.

**Comment by tleyden** [comment]
@ashvindersingh / @pasin -- one thing to consider here, is that it sounds like TodoLite failed silently.  What about popping up an error message when it can't connect to sync gateway?

**Comment by ashvindersingh** [comment]
@tleyden I think throwing an error (or online status bar or any kind of feedback telling user is not connected) would be great enhancement, it would have saved lot of time, if this feature was already existing.
