### ISSUE TITLE
Building with enterprise edition CouchbaseLite.framework   No known class method for selector 'modelForNewDocumentInDatabase:'

### ISSUE THREAD

**Issue by cesine** [couchbaselabs/ToDoLite-iOS#49]
ToDoLite-iOS/ToDoLite/List.m:53:24: No known class method for selector 'modelForNewDocumentInDatabase:'

```

// Creates a new task.
- (Task*) addTaskWithTitle: (NSString*)title withImage: (NSData*)image withImageContentType: (NSString*)contentType {
    Task *task = [Task modelForNewDocumentInDatabase:self.database];
    task.title = title;
    task.list_id = self;
    [task setImage:image contentType:contentType];
    return task;
}
```

**Comment by jamiltz** [comment]
Are you running the app with Couchbase Lite 1.1?
There are some changes to the CBLModel initializers in the 1.1 release.
Check this branch for the changes https://github.com/couchbaselabs/ToDoLite-iOS/tree/release/1.5.0.

**Comment by agonyou** [comment]
I built 1.1 and used it. This error went away. There is another error however. Filing a bug now.

**Comment by snej** [comment]
Reverted the 1.1 API changes, until the final GA release of CBL 1.1.

**Comment by cesine** [comment]
reverted in https://github.com/couchbaselabs/ToDoLite-iOS/commit/83f962d8d32c603df4f2a24323af7366afa9d206
