### ISSUE TITLE
Titled.m:29:19: No visible @interface for 'CBLModel' declares the selector 'initWithNewDocumentInDatabase:'

### ISSUE THREAD

**Issue by pejalo** [couchbaselabs/ToDoLite-iOS#51]
I'm a newb to Couchbase, getting this error when trying to build the project for the first time.

Couchbase lite Community 1.1.0-31
Xcode 6.3.2
OSX Yosemite 10.10.3

**Comment by snej** [comment]
Check out the `cbl_1.1` branch and build that. The master branch is still set to build with 1.0.4.

**Comment by pejalo** [comment]
Beautiful. On first glance this code looks cleaner. Thanks @snej !
