### ISSUE TITLE
Build error with Couchbase Lite 1.1

### ISSUE THREAD

**Issue by snej** [couchbaselabs/ToDoLite-iOS#52]
The method -[AppDelegate migrateOldVersionApp] calls the old removed version of [CBLManager replaceDatabaseNamed:…]. I haven’t seen that method before and I’m not quite sure what it’s doing or how to update it. @pasin, since you wrote it originally, could you update it to 1.1? (Or should we just remove the migration entirely?)

We need to fix this ASAP since this code is used in official tutorials.

**Comment by pasin** [comment]
I just removed the migration code to simplify the code.
