### ISSUE TITLE
Old facebook sdk causes ToDo lite iOS fail to compile 

### ISSUE THREAD

**Issue by ashvindersingh** [couchbaselabs/ToDoLite-iOS#55]
The current facebook sdk present in framework throws the below error when compiled: 
```
ld: '/Users/ashvinder/mobile_testing/ToDoLite-iOS/Frameworks/FBSDKLoginKit.framework/FBSDKLoginKit(FBSDKLoginCompletion.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
This issue is fixed when I upgraded to the latest facebook sdk from here:
https://developers.facebook.com/docs/ios and replaced the existing framework

However repo needs to be updated to include the latest facebook sdk framework.

**Comment by pasin** [comment]
Closed via https://github.com/couchbaselabs/ToDoLite-iOS/commit/b04ba92f01b1482f8d0e3b6a20c28050af3203b3.
