### ISSUE TITLE
Deleting a middle row task causes the task row below gone

### ISSUE THREAD

**Issue by pasin** [couchbaselabs/ToDoLite-iOS#57]
This issue cannot reproduce every time and happened while running with ForestDB Storage Engine. I believe that the issue is storage engine independent.

**Comment by pasin** [comment]
Confirmed that the issue happens only on ForestDB storage engine. It's also related to descending query.

**Comment by zgramana** [comment]
@pasin possibly also related to https://github.com/couchbase/couchbase-lite-ios/issues/641?

**Comment by snej** [comment]
Not really. That bug is about the inability to iterate _by sequence_ in descending order. View queries iterate by key.

**Comment by pasin** [comment]
Closed as fixed.
