### ISSUE TITLE
List doesn't sync

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/ToDoLite-iOS#58]
Steps to repro:

* Test against http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite12rc2-di/ (1.2 distributed index)
* Ashvinder running todolite-ios version ? and couchbase lite ios version (release/1.2)
* I'm running couchbase lite ios version from release/1.2 and todolite ios mater
* When Ashvinder adds a list and shares with me, I don't see it
* Seth running TodoLite-Android at commit - 15526b74b83bdac6d2d4a75779e75780e42699c2, release/1.2.0-sqlite
* I shared an "everyone" list and shared with Seth and Ashvinder, and added two items -- Seth deleted both of them, I never saw them deleted on my side.

**Comment by sethrosetter** [comment]
I was running TodoLite-Android at commit - 15526b74b83bdac6d2d4a75779e75780e42699c2, release/1.2.0-sqlite

**Comment by tleyden** [comment]
Moved to sg ticket

**Comment by snej** [comment]
Looks like that issue is couchbase/sync_gateway#1524
