### ISSUE TITLE
Enable all logging

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/ToDoLite-iOS#66]
Trying to debug https://github.com/couchbaselabs/ToDoLite-iOS/issues/65, would be easier if all logging (Sync, SyncVerbose) was enabled by default.

**Comment by snej** [comment]
It would get in the way of debugging other problems, i.e. with models or views or whatever. It also slows down performance a lot.

Can't you just run the app with command-line args? If that won't work, it just takes one or two lines of code to enable those logs in the CBLManager.
