### ISSUE TITLE
Checkmark ui bug

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/ToDoLite-iOS#72]
When sharing a list, if you select a person, the checkmark does not show. If you navigate back and the go to the share list again, you will see it. 

Expected: Click on a person to share with and a checkmark appears
Actual: Click on a person to share with and a checkmark does not appear

**Comment by pasin** [comment]
This is fixed https://github.com/couchbaselabs/ToDoLite-iOS/commit/ddfd619ab2edcf9355700af5163908be767f850e.
