### ISSUE TITLE
Add Nuke Support

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/ToDoLite-iOS#73]
Add a button that will delete all contents in a local database. We encounter trouble when manual testing of stale data replicating when launching the app, this would allow use to clear the data without cycling the target cluster.

**Comment by snej** [comment]
ToDoLite wasn't intended to be a testing tool, rather a sample app that was polished enough for real-world use and published on the app store. I don't think we should add testing-specific features like this to it, not unless we fork it and create a different app for testing.
